.github/workflows/workflow.yml
README.md
action.yml
lib/install.js
package-lock.json
package.json
src/darwin.sh
src/install.ts
src/linux.sh

- Add support for `php.ini` customization
- Copy `php.ini.default` to `php.ini` if required PHP version already installed in darwin.
- Fix debconf warnings #14

Add support for php.ini customization and fix bugs

---

src/darwin.sh

---
about: Fix installation on darwin after #32
labels: bug
---
- Do not exit after composer install 
- install `hirak/prestissimo` with sudo, else leads to permission errors.

Fix installation on darwin after #32

---

src/linux.sh

---
about: Remove exit after composer is installed. Fix #32
labels: bug
---
Remove exit after composer is installed. Fix #32

Remove exit after composer is installed. Fix #32

---

README.md
__tests__/features.test.ts
action.yml
lib/features.js
package-lock.json
package.json
src/features.ts

---
about: Add option to disable coverage drivers
---
Fixes #53 
Add option to disable coverage drivers
specifying `coverage: none` will disable `Xdebug` and `PCOV` if enabled.

Add option to disable coverage drivers

---

.github/workflows/workflow.yml
README.md
examples/codeigniter.yml
examples/laravel-mysql.yml
examples/laravel-postgres.yml
examples/laravel.yml
examples/slim-framework.yml
examples/symfony-mysql.yml
examples/symfony-postgres.yml
examples/symfony.yml
examples/yii2-mysql.yml
examples/yii2-postgres.yml
examples/zend-framework.yml
package-lock.json
package.json
src/scripts/darwin.sh
src/scripts/linux.sh

- Remove repeated command in `linux.sh` and run `update-alternatives` in parallel.
- Tap `exolnet/homebrew-deprecated` only for PHP `5.6` and `7.0`.
- Use `pwsh` for test commands in examples for uniformity across platforms.
- Improve links, examples and disable coverage section in `README.md`.
- Change `version` to `node-version` in the workflow.
- Bump version to 1.4.1

Fix scripts, README and examples

---

__tests__/config.test.ts
__tests__/coverage.test.ts
__tests__/extensions.test.ts
__tests__/utils.test.ts
lib/config.js
lib/coverage.js
lib/extensions.js
lib/install.js
lib/utils.js
package-lock.json
package.json
src/config.ts
src/coverage.ts
src/extensions.ts
src/install.ts
src/scripts/7.4.sh
src/scripts/darwin.sh
src/scripts/linux.sh
src/scripts/win32.ps1
src/utils.ts

- Improve logs.
- Shift from `Write-Host ` to `printf` on `windows` for logging.
- Shift from `echo` to `printf` on `macOS` and `ubuntu` for logging.
- Fix tests to cleanup files created.
- Fix `Xdebug` and `PCOV` installation on `PHP7.4` on ubuntu.
- Bump version to 1.4.3.

Release 1.4.3

---

.github/workflows/workflow.yml
README.md
lib/utils.js
src/scripts/7.4.sh
src/utils.ts

- Switch to `PHP7.4RC4` on `windows` and `macOS`
- Add support for extensions with pdo prefix like `pdo_mysql` and `pdo_sqlite`. Fixes #61 
- Fix test workflow to timeout `codecov` command

PHP 7.4RC4, pdo_* extensions and test workflow.

---

README.md
__tests__/extensions.test.ts
lib/extensions.js
package-lock.json
src/extensions.ts

Revert to `apt` for extensions as `apt-fast` gives exit-code as 0(success) even for errors.
Fixes wrong success messages for extensions which failed to install #71

Revert to apt for extensions

---

README.md
__tests__/extensions.test.ts
__tests__/install.test.ts
action.yml
lib/extensions.js
lib/install.js
src/extensions.ts
src/install.ts
src/scripts/linux.sh

---
about: PECL can now be setup by specifying `pecl: true as an input`
---
- Setup PECL when `pecl: true` is specified. #71 
- Use `apt-get` instead of wrapper `apt`.

Add PECL support on Linux

---

src/scripts/linux.sh
src/scripts/win32.ps1

- Fix php-fpm on linux in PHP 5.6 and 7.0
- Add a flag to skip checksum check if it fails in `Update-PhpCAInfo` call in `win32.ps1`. Fixes #88

Fix PHP-FPM in PHP and add a flag to skip checksum check if it fails

---

.github/workflows/experimental-workflow.yml
__tests__/coverage.test.ts
dist/index.js
src/coverage.ts

- Fix coverage log for `Xdebug` on PHP 8.0

Fix coverage log for Xdebug on PHP 8.0

---

README.md

This PR fixes a typo in the README, `extension` should actually be `extensions`.

Fix typo in available options

---

.github/matchers/phpunit.json
__tests__/install.test.ts
src/install.ts
src/matchers.ts

---
name:  🎉 Add problem matcher for PHPUnit
about: Add support for parsing PHPUnit output using problem matches
---
Adds a problem matcher, which parses output for warnings/errors. Documentation can be found here: https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md
The GitHub provided `setup-*` actions provide, [example](https://github.com/actions/setup-node/tree/7a3ce8362699742a34a1590e93c9b75e4d0d6dff/.github)
Matchers are registered using [toolkit commands](https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers). I've followed the implementation used by [`setup-node`](https://github.com/actions/setup-node/blob/7a3ce8362699742a34a1590e93c9b75e4d0d6dff/src/setup-node.ts#L27-L35)
---
> In case this PR introduced …

Add problem matcher for PHPUnit

---

src/scripts/linux.sh

Hotfix: Force install `libicu64` for PHP 8.0 as `icu` has been updated to `65.1` on ondrej's PPA

Hotfix: Force install libicu64 for PHP 8.0

---

__tests__/extensions.test.ts
src/extensions.ts

---
name: 🐞 Bug Fix,
about: The incorrect version of Xdebug is installed on PHP 5.6 and 7.0
labels: bug
---
See https://xdebug.org/docs/compat for the definitive compatibility table.

Fixed Xdebug version for PHP 5.6 and 7.0

---

src/scripts/win32.ps1

I just updated the PowerShell release script: now it builds an asset for every release.
Downloading such assets is preferable since:
- they contain updated metadata (useful for debugging)
- they contain only the production files
- they are pre-built: GitHub doesn't have to create a ZIP from a tag

Download release assets for PowerShell PhpManager

---

__tests__/extensions.test.ts
dist/index.js
src/extensions.ts

- Specify PHP version when installing ast. Fixes #305 
`apt-get install php-ast` is now `apt-get install php<version>-ast`.

Specify PHP version when installing ast

---

src/scripts/linux.sh

Switch to `apt-get` as `apt-fast` still gives wrong exit code. Fixes #308 and fixes #309

Switch to apt-get

---

src/scripts/win32.ps1

Let's avoid making an unnecessary REST call, and make the code a bit more solid (previously we assumed that PhpManager.zip is the first asset, but it may not be so in future).

Perform only one URL call to download latest PhpManager.zip asset

---

__tests__/tools.test.ts
dist/index.js
src/tools.ts

---
about: What about letting users specify a specific Composer version
---
This PR let users specify a specific Composer version. This is useful in particular to test Composer plugins which should support old Composer versions.

Allow installing a specific Composer version

---

examples/symfony-mysql.yml
examples/symfony-postgres.yml
examples/symfony.yml

---
name: Improve Symfony workflow
about: Install phpunit dependencies before runs the tests
---
Related discussion: related issue #376

issue #376 - Install phpunit dependencies before runs the tests

---

README.md
__tests__/extensions.test.ts
dist/index.js
src/extensions.ts
src/scripts/common.sh
src/scripts/darwin.sh
src/scripts/linux.sh

---
about: Allow extensions to be compiled from GitHub sources
---
Note: no discussion available as I built this for my own needs and want to start a discussion based on the changes I made.
This PR allows installing extensions from source. This is done by using a special extension format of the form `<extension>-<org>/<repo>@<version>`. Currently, only GitHub is supported and the repository is checked out using `git clone --recurse-submodules -b <version> https://github.com/<org>/<repo>`. This is supported on Linux and OSX, but not on Windows environments.
The rationale for adding this was that I didn't want to have separate steps depending on what extension version to install. This way, I can provide the repository URL and branch name as version …

Allow extensions to be compiled from GitHub sources

---

README.md

---
name: ⚙ Improvement on the readme
about: Update the list of supported tools
---
Related discussion: #187 
This PR adds `wp-cli` to the list of supported tools, also sorts the list of supported tools alphabetically. The PR #188 was merged a while ago, and it would be good that this tool is mentioned (I realized it was supported when I searched the issues 😄 ).
EDIT: Apparently, not only `wp-cli` was added, but `phplint` and `symfony-cli` as well.

Update readme with additional tools support

---

__tests__/tools.test.ts
dist/index.js
src/tools.ts

---
about: Update Phive configuration
---
Phive has released version `0.15.0` which ups the minimum supported PHP version to PHP 7.3.
This updates the switch statement for Phive to take this into account.
Ref: https://github.com/phar-io/phive/releases
**_P.S.: Hope I've done it right as I'm not familiar with writing code for GH actions._**

Update Phive configuration

---

src/scripts/tools/blackfire.sh

---
about: You found a bug
labels: bug
---
Related discussion: 
This PR changes `sudo service blackfire-agent start` to `sudo systemctl start blackfire-agent`

Use systemctl instead of services to install blackfire

---

README.md
__tests__/tools.test.ts
src/configs/tools.json

---
about: Add a new feature
---
Related discussion: #497
This PR adds support for the phpDocumentor tool via the `tools` input to setup-php.
phpDocumentor has also been aliased to `phpdoc` for convenience.
I have added a test to the `linux` test for the base name and to the `darwin` test for the alias.
👉🏻 Should I also add a test to the `windows` test ?
👉🏻 Should I add a test for downloading different versions ?
Note: running these scripts, automatically added two unrelated changes to the PR, which I have manually removed (had to disable the `pre-commit` hook to do so). The changes were to `package-lock.json` and to `dist/index.js`. Not sure what's going on there.
> In case this PR …

Tools: add support for phpDocumentor

---

README.md
__tests__/tools.test.ts
src/configs/tools.json

---
about: Add a new feature
---
Fixes #499
This PR adds support for the [PHP Parallel Lint](https://github.com/php-parallel-lint/PHP-Parallel-Lint) tool via the `tools` input to setup-php.
I have added a test to the `linux` test.

Tools: add support for PHP Parallel Lint

---

README.md
__tests__/tools.test.ts
src/configs/tools.json

---
about: Add a new feature
---
Fixes #502 
This PR adds support for the [PHPUnit Polyfills](https://github.com/Yoast/PHPUnit-Polyfills) tool via the `tools` input to setup-php.
I have added a test to the `linux` test and a second test with a specific version to the `darwin` test.
Note: running these scripts, automatically added two unrelated changes to the PR, which I have manually removed (had to disable the `pre-commit` hook to do so). The changes were to `package-lock.json` and to `dist/index.js`. Not sure what's going on there.

Tools: add PHPUnit Polyfills

---

.github/workflows/release.yml

---
about: Adding Github Actions to automatically publish to NPM and Github packages on creating a release
---
Related discussion: #507 
This PR adds a new Github action triggered on a release creation to automatically publish to NPM and Github Packages

ci: add github action to publish to npm and github packages

---

README.md
examples/cakephp-mysql.yml
examples/cakephp-postgres.yml
examples/cakephp.yml

---
about: You found a bug, want to improve something or add a new feature
---
~~All Composer commands used in CI should use `--no-interaction` to prevent them hanging in case interaction is expected.~~
~~This adds the `--no-interaction` argument to all Composer example code which did not have the argument yet.~~
All Composer commands used in CI should use `--no-interaction` to prevent them hanging in case interaction is expected. However, as setupPHP sets the `COMPOSER_NO_INTERACTION` flag (as of this version), this is not needed when using setupPHP.
This removes redundant `--no-interaction` arguments from the example code.
Also see: https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution

Example code: remove `--no-interaction` from Composer commands

---

README.md
__tests__/tools.test.ts
src/configs/tools.json

---
about: add a new feature
---
Related discussion: #560
This PR adds support for the [Churn-PHP](https://github.com/bmitch/churn-php) tool via the tools input to setup-php.
I have added a test to the `linux`, `darwin` and `windows` tests.

Tools: add support for Churn-PHP

---

.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/node.yml
.github/workflows/php.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

src/scripts/win32.ps1

---
about: PATH for the current procees needs to be updated with the newly installed php location
labels: bug
---
Related discussion: #608
This PR adds the location of the newly installed php tools to the PATH environment variable so that the current Powershell process can find them.
https://github.com/dino182/setup-php-testing/blob/2024ca4915dc4382028faf8e1bbd8984521564a3/.github/workflows/te …

Fix Add-Path for self-hosted Windows

---

README.md
__tests__/tools.test.ts
src/configs/tools.json

---
about: add a new feature
---
Related discussion: #613 
This PR adds support for [Laravel Pint](https://github.com/laravel/pint)

Add support for tool Laravel Pint

---

src/scripts/tools/symfony.sh

This PR make `symfony-cli` installation faster on Linux. Fixes #640.
Brew is available on Ubuntu runners but is very slow. Downloading the binary directly is faster.

🐞 Bug Fix: make symfony-cli installation faster on Linux

---

reset 1 qqc
src/configs/php_debug_packages
src/configs/tools.json
src/scripts/darwin.sh
src/scripts/extensions/source.sh
src/scripts/linux.sh
src/scripts/tools/ppa.sh
src/scripts/unix.sh

This PR adds the `thread-safe` build type to PHP setups.
The structure behind `debug` builds was slightly changed to better reflect the multiple build type concept (`release`, `debug` and `thread-safe` as defined in `unix.sh`).
Closes #649.

Add thread-safe setup support

---

__tests__/utils.test.ts
action.yml
dist/index.js
src/utils.ts

---
about: The php version input has a hardcoded default that stops the file input added in https://github.com/shivammathur/setup-php/pull/690 from working
labels: bug
---
Related discussion: https://github.com/shivammathur/setup-php/issues/629
The `php-version` input overrides any `php-version-file` provided, so it can't have a default value anymore, because that means https://github.com/shivammathur/setup-php/pull/690 doesn't fallback to the file correctly when no inputs are provided. …

Move php version default out of action.yml and update inputs

---

examples/sage.yml

fix a typo in the sage example

docs(example): fix a typo in the strategy of the sage example

---

__tests__/tools.test.ts
dist/index.js
src/tools.ts

---
name: ⚙ Improvement: Make PHPUnit versions compatible with the PHP version installed
about: If you just let the `phpunit` version be `latest` (by not defining a specific version), then it can be incompatible with the version of php defined.  This PR fixes that issue.
---
Related discussion: https://github.com/shivammathur/setup-php/issues/694
This PR makes an improvement to adding `phpunit` as a tool.  If you just let the `phpunit` version be `latest` (by not defining a specific version), then it can be incompatible with the version of php defined.  This PR adds version checking for phpunit and the php being setup.
For those last two points:
The `npm run release` failed with the following error:
```
➜  setup-php git:(phpunit-versions) ✗ npm run release …
```

Phpunit versions

---

README.md
__tests__/tools.test.ts
dist/index.js
src/configs/tools.json
src/tools.ts

Related discussion: https://github.com/shivammathur/setup-php/discussions/745
This PR add support for the tool jolicode/castor.
A demo repository is provided here: https://github.com/pyrech/castor-setup-php (see [this run](https://github.com/pyrech/castor-setup-php/actions/runs/5357609301/jobs/9718707236?pr=1) for a working demo with my fork)

Add support for tool jolicode/castor

---

__tests__/utils.test.ts
dist/index.js
src/utils.ts

---
about: Supports automatic detection of PHP version from composer.lock or composer.json file
---
This is related to #751 and should help with #629, #713, and #639.
This PR adds detection of [the "config.platform.php" setting available in composer.json](https://getcomposer.org/doc/06-config.md#platform) (which is also saved as platform-overrides.php in composer.lock), so that the required PHP version for an application using Composer will be automatically detected.
As the config.platform.php setting forces Composer to lock dependencies to a specific PHP version, it's a perfect way to detect the "required" version of PHP for a project without any risk of conflicts due to differing versions.
> In case this PR introduced TypeScript/JavaScript code …

Add automatic detection of required PHP version from Composer's platform setting

---

src/configs/tools.json

This PR proposes to add [Box](https://github.com/box-project/box) and [PHP-Scoper](https://github.com/humbug/php-scoper) as available tools.

feat: Add Box and PHP-Scoper as tools

---

README.md

---
about: Add documentation that php-version can come from the platform override version set in composer.lock or composer.json
---
Related discussion: None
This PR documents the behavior in the [readPHPVersion() method in utils.js](https://github.com/shivammathur/setup-php/blob/main/src/utils.ts#L431)
- [na] I have written test cases for the changes in this pull request
- [na] I have run `npm run format` …

Document php-version can come from platform overrides in composer.lock or composer.json

---

README.md
__tests__/tools.test.ts
src/configs/tools.json

---
about: add a new feature
---
Related discussion: #837 
This PR adds support for [ecs](https://github.com/easy-coding-standard/easy-coding-standard) tool to rest of the setup-php tools.

Add support for ecs

---

README.md
__tests__/tools.test.ts
src/configs/tools.json

---
about: New feature
labels: Enhancement
---
Related discussion: https://github.com/shivammathur/setup-php/discussions/858
This PR adds [composer-dependency-analyser](https://github.com/shipmonk-rnd/composer-dependency-analyser?tab=readme-ov-file#composer-dependency-analyser) tool support.

Support composer-dependency-analyser tool

---

.github/workflows/docs.yml

---
about: A new syntax error has been introduced with the latest commit for `.github/workflows/docs.yml`.
labels: bug
---
Related discussion: 
The latest commit for `.github/workflows/docs.yml` introduced a syntax error by using an [incomplete variable](https://github.com/shivammathur/setup-php/commit/981ce2a75a448a4f93da1745e08798b82942f0a7#diff-9cf2000c53760d837a449f874e53f792819108d3a4bf346336d0f7d082deae2cR24) - this PR fixes it.
> In case this PR introduced TypeScript/JavaScript code …

Fixed syntax error in `.github/workflows/docs.yml`

---

src/extensions.ts

This PR adds support to install Relay on PHP 8.4 and 8.5.

Relay: Support PHP 8.4 and 8.5

---

__tests__/tools.test.ts
src/configs/tools.json

---
---
It's about updating the repository name of the `php-cs-fixer` tools as it was moved. The previous name is still working.

Update php-cs-fixer repository organisation

---

README.md

As version 2 is the standard right now, make it clear by setting the v1 manually.

⚙ Improvement: Update docs
