shivammathur/setup-php

src/darwin.sh
src/linux.sh

This resolves https://github.com/shivammathur/setup-php/issues/12

Adding hirak/prestissimo to darwin and linux

---

.github/workflows/workflow.yml
README.md

---
name:  ⚙ Improvement
about: Fix codecov reporting and improve README
---
Fix codecov reporting and improve README

Fix codecov reporting and improve README

---

.github/workflows/workflow.yml
README.md
package.json

---
name: |
⚙ Improvement
about: You found a bug, have a failing test, want to improve something or add a new feature
labels: bug or enhancement
---
Not run workflow on *.md changes and fix links in README

Not run workflow on *.md changes and fix links in README

---

src/darwin.sh
src/linux.sh

---
name: |
⚙ Improvement
about: Improve composer installer
---
- Check to signature.
- Add error handling.
- See Also https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

Improve composer installer

---

.github/workflows/workflow.yml

|name|about|labels|
|--- |--- |---|
|Bug Fix|Fix workflow to run on all files except .md|bug|

Fix workflow to run on all files except .md

---

lib/features.js
src/features.ts

---
name: | Bug Fix
about: Add extension to `php.ini` in windows using `Add-Content`
labels: bug 
---

Add extension to php.ini in windows using Add-Content

---

src/7.4.sh
src/config.yaml

---
about: Install extensions with PHP7.4 on darwin.
---
Install extensions with PHP7.4 on darwin.
- see `src/config.yaml` for details

Install extensions with PHP7.4 on darwin.

---

config.yaml
lib/utils.js
src/7.4.sh
src/install.ts
src/utils.ts

name: Fix config.yaml path
about: Write `config.yaml` to runner directory, so that it can read the file.
labels: bug

Fix config.yaml path

---

__tests__/features.test.ts
__tests__/utils.test.ts
lib/features.js
lib/utils.js
package-lock.json
package.json
src/7.4.sh
src/darwin.sh
src/features.ts
src/linux.sh
src/utils.ts

Fix logs and 7.4 on darwin
- `kerberos` should be `krb5`
- Improve logs and make sure they don't echo out of turn.
- Clean `7.4.sh`

Fix logs and 7.4 on darwin

---

__tests__/features.test.ts
__tests__/utils.test.ts
lib/features.js
lib/utils.js
src/features.ts
src/linux.sh
src/utils.ts

---
name: | 🐞 Bug Fix
about: Fix xdebug version
labels: bug
---

Fix xdebug version

---

README.md
example/laravel.yml

---
This PR to resolve #46 
This PR adds an example directory with a `laravel.yml` example.

adding laravel with mysql example

---

example/laravel-postgres.yml

Fix example laravel with postgres

---

README.md

Fix example links in `README.md`

Fix links in README. Broken in #51

---

lib/extensions.js
src/extensions.ts
src/scripts/darwin.sh

🐞 Bug Fix
Fix `php.ini` file path in enableExtensionUnix and `ext_dir` in `darwin.sh`

Fix enableExtensionUnix

---

action.yml

Revert action.yml changes

---

README.md

---
name: ⚙ Update cache dependencies section in README
about: Add configuration to cache composer's internal directory instead of vendor
---
- Add configuration to cache composer's internal directory instead of vendor
- Bump [`action/cache`](https://github.com/actions/cache) version to `v1`
- Add conditional configuration until actions/cache/issues/39 is fixed.

Update cache dependencies section in README

---

README.md

- Remove `windows-2016`  actions/virtual-environments#68
- Bump `macOS` version to `10.15` Catalina - actions/virtual-environments#80

Update OS/virtual environments available

---

README.md

Fix matrix usage yml

---

README.md
__tests__/extensions.test.ts
lib/extensions.js
package-lock.json
package.json
src/extensions.ts

- Edit extensions installation on `PHP7.4`.
- Use runner context in cache `yml`.
- Bump version to `1.5.0`.

Edit extension installation, update cache yml

---

README.md
package-lock.json
package.json
src/scripts/7.4.sh

- Bump `PHP 7.4` version on `windows` and `macOS` to `7.4.0 RC6`
- Bump version to `1.5.2`

Bump PHP7.4 version on windows and macOS

---

src/scripts/win32.ps1

- Fix check for existing extensions on windows. Fixes #80

Fix check for existing extensions on windows

---

__tests__/extensions.test.ts
dist/index.js
src/extensions.ts
src/scripts/win32.ps1

---
name: ⚙ Simplify win32 script
about: The win32 script is overly complex: let's simplify it
---
Related issue: #85

Simplify win32 script

---

.github/workflows/workflow.yml
README.md
examples/bedrock.yml
examples/codeigniter.yml
examples/laravel-mysql.yml
examples/laravel-postgres.yml
examples/laravel.yml
examples/lumen-mysql.yml
examples/lumen-postgres.yml
examples/lumen.yml
examples/phalcon-mysql.yml
examples/phalcon-postgres.yml
examples/sage.yml
examples/slim-framework.yml
examples/symfony-mysql.yml
examples/symfony-postgres.yml
examples/symfony.yml
examples/yii2-mysql.yml
examples/yii2-postgres.yml
examples/zend-framework.yml
package-lock.json
src/scripts/7.4.sh
src/scripts/linux.sh
src/scripts/win32.ps1

- Shift to rotating stable tags
- Bump to 7.4.0 stable version

Switch to v1 tag and stable PHP 7.4.0

---

src/scripts/linux.sh
src/scripts/win32.ps1

- Fix phpdbg version and install on PHP7.4. Fixes #93 
- Update Update-PhpCAInfo command in win32.ps1

Fix phpdbg and improve windows script.

---

__tests__/extensions.test.ts
dist/index.js
src/extensions.ts
src/scripts/gearman.sh

---
about: Gearman extension
---
Related issue: #116 
This PR adds a possibility to isntall gearman extension

Gearman extension

---

src/scripts/darwin.sh
src/scripts/linux.sh

Fix add_extension on linux and macOS

---

__tests__/coverage.test.ts
dist/index.js
package-lock.json
src/coverage.ts

Remove coverage drivers completely if requested

---

__tests__/extensions.test.ts
dist/index.js
src/extensions.ts
src/scripts/phalcon.sh

Hotfix to support phalcon after v4 release

---

README.md
__tests__/install.test.ts
dist/index.js
src/install.ts
src/scripts/ext/phalcon.sh

- Setup tools before extensions
- Improve `phalcon.sh` script
- Fix README

1.7.0 Hotfix

---

package-lock.json
package.json
src/scripts/linux.sh

- Delete extension files instead of using `apt-get remove` in `remove_extension` in `linux`

Improve remove_extensions in linux

---

action.yml

Fix description in `actions.yml`

Fix description in actions.yml

---

src/scripts/linux.sh

- Update ppa. Fixes 5.6 and 7.0

Update ppa before installing PHP

---

__tests__/tools.test.ts
dist/index.js
src/scripts/darwin.sh
src/scripts/linux.sh
src/tools.ts

---
name: 🎉 Adds WP-CLI as a tool.
about: You found a bug, want to improve something or add a new feature
---
> We wish to have discussions in Issues. A single issue may be targeted by multiple PRs.
> If you're offering a new feature or fixing anything, we'd like to know beforehand in Issues,
> and potentially we'll be able to point development in a particular direction.
Related issue: 
Closes #187 
This PR adds support WP-CLI as a **tool**. The windows setup is lacking because I don't know PowerShell. Sorry :man_shrugging:.

New Tool: WP-CLI

---

README.md
__tests__/extensions.test.ts
__tests__/utils.test.ts
dist/index.js
examples/blackfire.yml
src/extensions.ts
src/scripts/ext/blackfire.ps1
src/scripts/ext/blackfire.sh
src/scripts/ext/blackfire_darwin.sh
src/utils.ts

This PR adds blackfire to all operating systems with php 5.6+ 
Fixes #191

🎉 Add blackfire extenstion

---

dist/index.js
package-lock.json
package.json
src/scripts/darwin.sh
src/scripts/linux.sh
src/scripts/win32.ps1

- Fix logs of `blackfire` setup
- Update dependencies

Hotfix 2.1.0

---

src/scripts/darwin.sh
src/scripts/linux.sh

---
about: Bugs about Blackfire integration
labels: bug
---
> If you're fixing a bug, adding a new feature or improving something please provide the details in Issues,
Related issue: #247 #248
This PR removes `sudo` when it's not needed for Blackfire configuration.

Remove sudo for Blackfire config when it's not needed

---

.github/workflows/workflow.yml
README.md
__tests__/extensions.test.ts
__tests__/tools.test.ts
dist/index.js
src/extensions.ts
src/scripts/darwin.sh
src/scripts/ext/oci.ps1
src/scripts/ext/oci.sh
src/scripts/win32.ps1
src/tools.ts

---
name:  🎉 New Feature
about: I want to add a new feature
---
Related issue: #250
This PR adds `ergebnis/composer-normalize` as a tool

Enhancement: Add ergebnis/composer-normalize as tool

---

README.md
__tests__/tools.test.ts
dist/index.js
src/tools.ts

---
name:  🎉 New Feature
about: I want to add a new feature
---
Related issue: #250
This PR adds `maglnet/ComposerRequireChecker` as a tool

Enhancement: Add maglnet/ComposerRequireChecker as tool

---

README.md
__tests__/tools.test.ts
dist/index.js
src/tools.ts

This PR
💁‍♂️ Thanks to https://plugins.jetbrains.com/plugin/5919-lines-sorter.

Fix: Keep list of tools sorted

---

src/configs/config.yaml

This PR
💁‍♂️ Thanks to https://plugins.jetbrains.com/plugin/5919-lines-sorter.

Fix: Keep extensions and options sorted

---

src/scripts/win32.ps1

I just started to publish PhpManager to GitHub Releases too

Use releases instead of tags to download PowerShell PhpManager

---

README.md

no need for cs2pr, it is built-in :)

PHPStan is GH Actions-friendly

---

dist/index.js
package-lock.json
package.json
src/scripts/darwin.sh
src/scripts/linux.sh
src/scripts/tools/grpc_php_plugin.ps1
src/scripts/win32.ps1

Switch to environment files. Apply GHSA-mfwh-5m23-j46w (CVE-2020-15228)

---

README.md

---
about: Updates readme badge ;)
labels: bug
---

PHP 8.1 supported too

---

README.md

---
name: ⚙ Improvement on the readme
about: Fixed errors in documentation.
---
I found a mistake in the README and fixed it.

Update readme about composer (Fixed errors)

---

src/configs/tools.json

---
about: You found a bug
labels: bug
---
N/A
While the PHPCPD and PHPUnit tools use the [same function under the hood](https://github.com/shivammathur/setup-php/blob/1fa3ba1b162e818eed12eed233c9837299574948/src/tools.ts#L461-L473), I have the impression that the `function` keyword should be the tool name.
If that's correct, this should fix it.
**_This change is already covered by existing tests_**

Fix apparent typo

---

src/scripts/win32.ps1

Imagick now has DLLs in the extension zip and using `Install-PhpExtensionPrerequisit` is not required and thus has been removed from PhpManager.
Ref: https://github.com/mlocati/powershell-phpmanager/issues/93

Stop using Install-PhpExtensionPrerequisite for imagick

---

.github/workflows/docs.yml

---
about: CI
---
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/upload-artifact/releases

GH Actions: version update for various predefined actions

---

.github/workflows/php.yml

Related discussion: https://github.com/shivammathur/setup-php/issues/616
This PR [briefly explain what it does]

Demo PHP8.2+gd failure

---

README.md

---
about: Docu improvement
labels: bug
---
This PR fix the URL for symfony flex documentation page

Change symfony flex url

---

README.md

---
about: v2 throws deprecation warning so use v3
labels: bug 
---

doc: fix otudated github action version

---

src/utils.ts

---
about: Small fix in DocBlock
labels: Enhancement
---
I found a small inconsistency in DocBlock. This PR should fix it.

Fix DocBlock in `utils.ts`

---

README.md

I noticed that "For" was incorrectly capitalized, but also rewrote the sentence slightly because it was a bit redundant to be saying "for other tools" at the start and then "any tools" at the end.

docs: improve sentence structure slightly

---

src/scripts/extensions/sqlsrv.sh

---
about: You found a bug, want to improve something or add a new feature
labels: bug or enhancement
---
Related discussion: 
This PR [briefly explain what it does]

Use sqlsvr 5.11.1 on PHP 8

---

.github/workflows/docs.yml

Related discussion: _N/A_
The [wiki](https://github.com/shivammathur/setup-php/wiki) is missing details on the installed extensions on PHP 8.3.
This PR adds PHP 8.3 to the docs workflow to generate the information for the wiki.

GH Actions/docs workflow: generate extensions page for PHP 8.3

---

README.md

---
about: list of supported PHP versions in README
---
This PR updates the list of PHP versions in the README. Specifically, 8.2 is marked as only receiving security fixes, see announcement at <https://news-web.php.net/php.internals/126138>.

README: update list of PHP versions

---

README.md

---
name: ⚙ Improvement 
about: Update README about version of `ubuntu-latest` label
---
This PR update the `ubuntu-latest` according to https://github.com/actions/runner-images?tab=readme-ov-file#available-images

Move `ubuntu-latest` to 24.04

---

src/scripts/tools/ppa.sh

see https://github.com/shivammathur/setup-php/issues/927

switch to launchpadcontent #927 close
